In [210]:
import numpy as np

possible_resistors = np.array([
    100.0,
    320.0,
    1000.0,
    800.0
])

resistor_count = 10

In [ ]:
import numpy as np

def get_binary_masks(n):
    # it works idk how but it works
    needed_bits = int(2**n-1).bit_length()
    masks = np.unpackbits(np.flip(np.arange(2**n, dtype=np.uint64).view(np.uint8))).reshape(2**n, 64)[:,-needed_bits:]
    return masks[::-1]

In [188]:
def convert_to_bits(number):
    print(np.flip(np.array([number], dtype=np.uint64).view(np.uint8)))
    return np.unpackbits(np.flip(np.ara(number, dtype=np.uint64).view(np.uint8))).reshape((len(number), 64))

In [215]:
def convert_to_base_index(num, index, base):
    return (num//(base**index))%base

vconvert_to_base_index = np.vectorize(convert_to_base_index)

def compute_all_resistor_configuration(resistors_types, count):
    base = len(resistors_types)
    possible_configs = base**count
    all_configurations = vconvert_to_base_index(np.arange(possible_configs)[:, None], np.arange(count)[::-1], base)
    return all_configurations


In [216]:
# testing compute_all_resistor_configuration
print(compute_all_resistor_configuration(possible_resistors, resistor_count))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 2]
 ...
 [3 3 3 ... 3 3 1]
 [3 3 3 ... 3 3 2]
 [3 3 3 ... 3 3 3]]


In [225]:
def resistor_replacement(index, possible_resistors):
    print(index, possible_resistors)
    return possible_resistors[index]

vresistor_replacement = np.vectorize(resistor_replacement, excluded=['possible_resistors'])

def compute_configurations(configurations, possible_resistors, resistor_count):
    masks = get_binary_masks(len(possible_resistors))

    print(vresistor_replacement(configurations, possible_resistors))


In [226]:
configurations = compute_all_resistor_configuration(possible_resistors, resistor_count)
compute_configurations(configurations, possible_resistors, resistor_count)

0 100.0


IndexError: invalid index to scalar variable.